# 1. Ana Docker Şeması ile Tam Uyumlu Veritabanı Ayarları
spring.datasource.url=jdbc:postgresql://android_db:5432/customer_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# 2. Hibernate / JPA Ayarları
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# 3. Sunucu İç Portu
server.port=8080